apiVersion: v1
kind: Pod
metadata:
  name: lab2-paulthottappillybostonhousing
spec:
  restartPolicy: Never
  containers:
  - name: lab2-paulthottappillybostonhousing
    image: crdsba6190deveastus001.azurecr.io/lab2_paulthottappilly:latest
    volumeMounts: 
      - name: datalake
        mountPath: "/mnt/datalake/"
        readOnly: false
    # command: ["/bin/bash", "-c"] 
    # args: ["./run.py"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    # resources:
    #   limits:
    #     memory: "2Gi"
    #     cpu: "200m"
  imagePullSecrets:
    - name: acr-secret
  volumes:
    - name: datalake
      persistentVolumeClaim:
        claimName: azure-blob-pvc